### ISSUE TITLE
What changed in hiplogging==2.0.0?

### ISSUE THREAD

**Issue by jaapz** [invernizzi/hiplogging#12]
So hiplogging 2.0.0 is released. This is a major version bump, so I am curious as to what changed in the package? Could you maybe write a changelog?

**Comment by invernizzi** [comment]
We moved to the new Hipchat API (v2). Hiplogging is now using "HypChat" instead of "hipchat"  (see #10).

**Comment by jaapz** [comment]
Neat, thanks for clarifying
