### ISSUE TITLE
"Invalid OAuth session" or "Forbidden"

### ISSUE THREAD

**Issue by gunthercox** [invernizzi/hiplogging#14]
I have been unable to get messages to post to hipchat.

If I create an access token through the interface at https:/my_hipchat_name.hipchat.com/admin/api, this results in an "Invalid OAuth session" error message.

```
line 58, in request
    resp = super(_requests, self).request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hypchat/requests.py", line 430, in request
    raise _http_errors[rv.status_code](rv.text, response=rv)
hypchat.requests.HttpUnauthorized: {
  "error": {
    "code": 401,
    "message": "Invalid OAuth session",
    "type": "Unauthorized"
  }
}
```

Otherwise, if I generate a _personal access token_ under account settings, I get a more descriptive permission error message:

```
hypchat.requests.HttpForbidden: {
  "error": {
    "code": 403,
    "message": "This action requires one of the following scopes: [u'view_group', u'view_room']",
    "type": "Forbidden"
  }
}
```

I have been testing with the example code in the readme. I'm assuming that a change may have occurred in HipChat's API. Can you replicate this issue on your end?

**Comment by gunthercox** [comment]
This was an error that was my fault. I didn't properly select the authorization level when I was creating my  access token. Apologies for the false alarm.

**Comment by thakral729** [comment]
Hi
I'm getting same sort of error, while trying to set up Errbot with Hipchat enterprise server.

Could you please share what changes have you done or your config.py?

Thanks...!!!

**Comment by gunthercox** [comment]
Hi @thakral729, I don't have any code that I can share. In my case, I had the wrong permissions set for the auth token that I had created using the developer interface that Gitter provides. To fix it I just needed to create a new auth token with the correct permissions set.
