### ISSUE TITLE
Support for message_format and other rooms/message parameters

### ISSUE THREAD

**Issue by woozyking** [invernizzi/hiplogging#4]
Hi,

According to https://www.hipchat.com/docs/api/method/rooms/message the default API endpoint behavior has `message_format` in as `html`. Could you add support for the full array of parameters?

I think if you have no particular reason to use the raw API wrapper from `python-simple-hipchat`, then you can easily replace the API call in [`Hipchat.send_message`](https://github.com/invernizzi/hiplogging/blob/master/hiplogging/__init__.py#L27) to the already provided `message_room` method from [`python-simple-hipchat`](https://github.com/kurttheviking/python-simple-hipchat/blob/master/hipchat/__init__.py#L70)

Leo

**Comment by invernizzi** [comment]
Hi Leo,
thanks for this info! I've updated the library.
Ciao!
  Luca

**Comment by woozyking** [comment]
@invernizzi sorry I think you missed a part of the issue. Using the `message_room` method provided is a good start, but it still doesn't address the issue where `send_message` method doesn't support the fully array of arguments that `message_room` supports.
