### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by ssenaria** [invernizzi/hiplogging#6]
Which api version is this for? I looked at `/usr/lib/python2.6/site-packages/hipchat/__init__.py` and noticed it points to "/v1" endpoint and I'm unable to authenticate. I tried using both API tokens for api1 and api2 but I keep getting "urllib2.HTTPError: HTTP Error 401: Unauthorized"

**Comment by ssenaria** [comment]
you mean this package? `python-simple-hipchat-0.3.3-1.noarch` I already have it installed.

I got it to work. This time I imported the hipchat module `import hipchat` and created an admin privilege token. I was using a notification token. Any way to use a notification token instead?

**Comment by invernizzi** [comment]
Great! I made the readme file clearer. I'm afraid a notification token won't be enough, as the library needs to pull the list of rooms, so that you can use your human-friendly name for a room (e.g., my-fantastic-room) instead of a long nonsensical id.
