### ISSUE TITLE
Python 2.4 compatible

### ISSUE THREAD

**Issue by ssenaria** [invernizzi/hiplogging#7]
Is the code compatible w/ Python 2.4?

I'm getting the following errors.

    File "/usr/lib/python2.4/site-packages/hiplogging/__init__.py", line 3 
    from __future__ import print_function`
    SyntaxError: future feature print_function is not defined

**Comment by invernizzi** [comment]
Hi,
could you try with the current version? I have no python2.4 readily available, but I fixed the bug that was affecting you.

**Comment by ssenaria** [comment]
Works thx!
