### ISSUE TITLE
Hiplogging not working any more

### ISSUE THREAD

**Issue by mkannan555** [invernizzi/hiplogging#8]
I am trying hiplogging to send notifications to HipChat rooms. But I am getting "401" unauthorised access. But with the same token i am able to send it via curl cmdline utility.

```
#!/bin/bash

ROOM_ID=XXXXXXXX
AUTH_TOKEN='XXXXXXXXXXXX'
MESSAGE="Hello world!"

curl -v --header "content-type: application/json" --header "Authorization: Bearer $AUTH_TOKEN" -X POST \
  -d "{\"message\":\"Test Message\",\"color\":\"green\"}" https://api.hipchat.com/v2/room/$ROOM_ID/notification
```

I think the issues is that the V2 REST API could have been updated making the current version of HipLogging incompatible.

Guys can you please fix it.

**Comment by invernizzi** [comment]
Hi Kannan,
I just run my tests, and everything seems to run fine. To talk to HipChat, Hiplogging is using "python-simple-hipchat", which is using the V1 REST API.
Could you check if the token you have is an admin token? A normal "notification" token will not work (check out the README).
